title: "Delina Yetbarek's Resume"
description: "A simple online resume"
url: "https://delinayetbarek03.github.io/PersonalWebsite"
baseurl: "/resume"
remote_theme: "LeNPaul/academic"
plugins:
  - jekyll-remote-theme
